image: Visual Studio 2019
build_script:
  - ps: dotnet cake build.cake --bootstrap
assembly_info:
  # We'll version the binaries and the NuGet package in the build script
  patch: false

  # We'll run the tests in the build script
test: off
# AppVeyor will create a release tag if a matching one does not exist
# hence triggering another build
skip_tags: true
skip_commits:
  files:
    - LICENSE
    - README.md
# `install` will run before `build_script`
install:
  # Cake build is targeting `.NET Core` `2.2.0`, so we can safely install the latest `SDK`
  # The `SDK` is required to restore, build, publish... a `.NET Core` application
  # https://www.microsoft.com/net/download/windows
  - ps: .\build\dotnet-install.ps1 -Channel Current
  - ps: dotnet tool install --global Cake.Tool --version 0.33.0
