# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- integration/*

pool:
  vmImage: ubuntu-latest

steps:
- task: ShellScript@2
  inputs:
    scriptPath: build-in-docker.sh

- publish: $(System.DefaultWorkingDirectory)/artifacts/nupkg
  artifact: metaprint-tool

- download: current
  artifact: metaprint-tool